---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "type: dependencies"
    commit-message:
      prefix: "build"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "type: dependencies"
    commit-message:
      prefix: "docs"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "type: dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"
