# https://github.com/marketplace/pull-request-size
---
XS:
  name: "size: xs"
  lines: 0
  color: "00ff3a"
S:
  name: "size: s"
  lines: 10
  color: "9cff00"
M:
  name: "size: m"
  lines: 30
  color: "efff00"
L:
  name: "size: l"
  lines: 100
  color: "ff7500"
XL:
  name: "size: xl"
  lines: 500
  color: "c60404"
XXL:
  name: "size: xxl"
  lines: 1000
  color: "b60205"
