---
name: Pull request cleanup

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  handle-labels:
    runs-on: ubuntu-latest
    name: Handle labels
    steps:
      - name: Remove triage label
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        continue-on-error: true
        with:
          labels: "status: needs triage"

      - name: Remove review label
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        continue-on-error: true
        with:
          labels: "status: needs review"

      - name: Add merged label if merged
        if: github.event.pull_request.merged == true
        uses: actions-ecosystem/action-add-labels@v1.1.3
        with:
          labels: "status: merged"

